### ISSUE TITLE
cannot find value `REPO_REMOTE` in module `pkgutils`

### ISSUE THREAD

**Issue by bjackson** [redox-os/installer#1]
Build fails due to the latest commit in pkgutils that removes REPO_REMOTE

https://github.com/redox-os/pkgutils/commit/a93e7d658e7b6120614bca2f1b8ade5073c23621

```
error[E0425]: cannot find value `REPO_REMOTE` in module `pkgutils`
   --> installer/src/install.rs:159:58
    |
159 |         let remote_path = format!("{}/{}.tar", pkgutils::REPO_REMOTE, packagename);
    |                                                          ^^^^^^^^^^^ not found in `pkgutils`
```

**Comment by ametisf** [comment]
It's this commit [redox-os/pkgutils@260a657](https://github.com/redox-os/pkgutils/commit/260a6578ab37454cfe902fafd2d41ec670f779e4)

**Comment by jackpot51** [comment]
Thanks, I am fixing it now

**Comment by jackpot51** [comment]
This should be fixed now
